# This file will be included by the Makefile under the project directory.

FLOAT_O := $(FLOAT:.a=.o)
FLOAT_VFPRINTF_O := $(dir $(FLOAT))FLOAT_vfprintf.o
FLOAT_VFPRINTF_LINUX_O := $(dir $(FLOAT))FLOAT_vfprintf-linux.o

FLOAT_A_OBJ := $(FLOAT_O) $(FLOAT_VFPRINTF_O)
FLOAT_LINUX_A_OBJ := $(FLOAT_O) $(FLOAT_VFPRINTF_LINUX_O)

$(FLOAT): $(FLOAT_A_OBJ)
	ar r $@ $^

$(FLOAT_LINUX): $(FLOAT_LINUX_A_OBJ)
	ar r $@ $^

$(FLOAT_O): $(LIB_COMMON_DIR)/FLOAT/FLOAT.c
	$(call make_command, $(CC), $(testcase_CFLAGS), cc $@, $<)

$(FLOAT_VFPRINTF_O): $(LIB_COMMON_DIR)/FLOAT/FLOAT_vfprintf.c
	$(call make_command, $(CC), $(testcase_CFLAGS), cc $@, $<)

$(FLOAT_VFPRINTF_LINUX_O): $(LIB_COMMON_DIR)/FLOAT/FLOAT_vfprintf.c
	$(call make_command, $(CC), $(testcase_CFLAGS) -DLINUX_RT, cc $@, $<)
